<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = array(
            array('id' => '1','name' => 'EGGS','unit' => 'Pcs','category' => 'Food items','supplier' => 'Trufflez','cost' => '0.05'),
            array('id' => '2','name' => 'SUGAR','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.27'),
            array('id' => '3','name' => 'CARDAMON','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '11.5'),
            array('id' => '4','name' => 'VANILLA','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '19.02'),
            array('id' => '5','name' => 'BLOSSOM WATER (BOTTLE)','unit' => 'ML','category' => 'Food items','supplier' => '','cost' => '1.25'),
            array('id' => '6','name' => 'OLIVE OIL','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.398'),
            array('id' => '7','name' => 'PISTACHIO','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '8'),
            array('id' => '8','name' => 'FLOUR','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.145'),
            array('id' => '9','name' => 'BAKING POWDER','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '4.5'),
            array('id' => '10','name' => 'SALT','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.214'),
            array('id' => '11','name' => 'ORANGE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.6'),
            array('id' => '12','name' => 'HAZELNUTS','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '4'),
            array('id' => '13','name' => 'SUNFLOWER PULP','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '2.48'),
            array('id' => '14','name' => 'SUNFLOWER OIL','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.583'),
            array('id' => '15','name' => 'ANISE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '3.95'),
            array('id' => '16','name' => 'SESAME SEEDS','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.5'),
            array('id' => '17','name' => 'KALONJI SEEDS','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.25'),
            array('id' => '18','name' => 'SAFFRON','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '4.722'),
            array('id' => '19','name' => 'BUTTER','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '10.5'),
            array('id' => '20','name' => 'POWDER SUGAR','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.295'),
            array('id' => '21','name' => 'FLORENTA SUGAR','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '2.4'),
            array('id' => '22','name' => 'PISTACHIO SLICE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '12'),
            array('id' => '23','name' => 'ALMOND SLICE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '12'),
            array('id' => '24','name' => 'ALMOND','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '3'),
            array('id' => '25','name' => 'COCOA POWDER','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '6'),
            array('id' => '26','name' => 'MILK CHOCOLATE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '2.5'),
            array('id' => '27','name' => 'EXPRESSO','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '10.88'),
            array('id' => '28','name' => 'BISCUIT','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.875'),
            array('id' => '29','name' => 'WHIPPING CREAM','unit' => 'ML','category' => 'Food items','supplier' => '','cost' => '1.5'),
            array('id' => '30','name' => 'PISTACHIO PASTE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '7.7'),
            array('id' => '31','name' => 'MILK  ','unit' => 'ML','category' => 'Food items','supplier' => '','cost' => '0.333'),
            array('id' => '32','name' => 'CREAM','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '3.4'),
            array('id' => '33','name' => 'BASE 100','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '11.25'),
            array('id' => '34','name' => 'MISTICA','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '8.667'),
            array('id' => '35','name' => 'WHITE CHOCOLATE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '2.5'),
            array('id' => '36','name' => 'PACKAGING','unit' => 'Pcs','category' => 'NON FOOD','supplier' => '','cost' => '0.37'),
            array('id' => '37','name' => 'ALMOND POWDER','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '4'),
            array('id' => '38','name' => 'EGG WHITE FROZEN','unit' => 'Pcs','category' => 'Food items','supplier' => '','cost' => '0.05'),
            array('id' => '39','name' => 'YEAST','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.273'),
            array('id' => '40','name' => 'BREAD IMPROVER','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.273'),
            array('id' => '41','name' => 'KIRI CHEESE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '2.95'),
            array('id' => '42','name' => 'COLOUR','unit' => 'ML','category' => 'Food items','supplier' => '','cost' => '5.5'),
            array('id' => '43','name' => 'LETTUCE LEAVES','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.98'),
            array('id' => '44','name' => 'GOUDA CHEESE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '2.3'),
            array('id' => '45','name' => 'DRIED TOMATO','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '6'),
            array('id' => '46','name' => 'TOBACK CHEESE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '5.8'),
            array('id' => '47','name' => 'ZATTAR','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '3.25'),
            array('id' => '48','name' => 'OLIVES','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.8'),
            array('id' => '49','name' => 'ROUMI CHEESE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '2.5'),
            array('id' => '50','name' => 'STAWBERRY JUICE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.375'),
            array('id' => '51','name' => 'GREEN CHEESE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.79'),
            array('id' => '52','name' => 'PURPLE CHEESE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.79'),
            array('id' => '53','name' => 'CHERRY','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '15'),
            array('id' => '54','name' => 'DATES','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '2.99'),
            array('id' => '55','name' => 'DATES SYRUP','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '2.99'),
            array('id' => '56','name' => 'WALNUT','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '7'),
            array('id' => '57','name' => 'BISCUIT OREO','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.15'),
            array('id' => '58','name' => 'FRESH MANGO','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.94'),
            array('id' => '59','name' => 'MANGO PASTE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '5'),
            array('id' => '60','name' => 'FRUIT PASTE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '4.142'),
            array('id' => '61','name' => 'ICING SUGAR','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1'),
            array('id' => '62','name' => 'HONEY','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.45'),
            array('id' => '63','name' => 'PISTACHIO POWDER','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '8.5'),
            array('id' => '64','name' => 'CARAMEL SAUCE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.597'),
            array('id' => '65','name' => 'DARK CHOCOLATE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '19.55'),
            array('id' => '66','name' => 'CREAM ( CHEF FATHY )','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0'),
            array('id' => '67','name' => 'HAZELNUT POWDER','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '4.5'),
            array('id' => '68','name' => 'WAFER BOX','unit' => 'Pcs','category' => 'Food items','supplier' => '','cost' => '3.498'),
            array('id' => '69','name' => 'RAHASH','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '3.5'),
            array('id' => '70','name' => 'PENAUT','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.25'),
            array('id' => '71','name' => 'PENAUT BUTTER','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.1'),
            array('id' => '72','name' => 'CARAMEL ','unit' => 'Grams','category' => 'Food items','supplier' => 'Wasak','cost' => '3.5'),
            array('id' => '73','name' => 'SNICKERS PACKAGING 6 PIECES','unit' => 'Pcs','category' => 'Food items','supplier' => '','cost' => '0.5'),
            array('id' => '74','name' => 'SNICKERS PACKAGING 3 PIECES','unit' => 'Pcs','category' => 'Food items','supplier' => '','cost' => '0.25'),
            array('id' => '75','name' => 'DRY APPIERCUT','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.88'),
            array('id' => '76','name' => 'RAISINS','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.35'),
            array('id' => '77','name' => 'CASHAW','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '3.4'),
            array('id' => '78','name' => 'CHERRY PASTE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '16'),
            array('id' => '79','name' => 'Gram Flour','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.215'),
            array('id' => '80','name' => 'Brown Flour','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.145'),
            array('id' => '81','name' => 'COFFEE PASTE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '4.17'),
            array('id' => '82','name' => 'PECAN','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '7'),
            array('id' => '83','name' => 'STAWBERRY PASTE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '3.067'),
            array('id' => '84','name' => 'GOLD POWDER','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '10.2'),
            array('id' => '85','name' => 'TAHINA','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.37'),
            array('id' => '86','name' => 'FEUILLETINE CRISPY CREPE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '3.3'),
            array('id' => '87','name' => 'GELATO','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.3'),
            array('id' => '88','name' => 'Condensed Milk','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.53'),
            array('id' => '89','name' => 'Frozen Baklawa','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.35'),
            array('id' => '90','name' => 'PACKING SODA','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.595'),
            array('id' => '91','name' => 'CINNAMON','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.35'),
            array('id' => '92','name' => 'FROZEN KUNAFA','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '6.995'),
            array('id' => '93','name' => 'GEE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '7.25'),
            array('id' => '94','name' => 'CORN FLOUR','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '8.16'),
            array('id' => '95','name' => 'STRAWBERRY JAM','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.595'),
            array('id' => '96','name' => 'ALMOND CREAM','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '7.708'),
            array('id' => '97','name' => 'ROSE WATER','unit' => 'ML','category' => 'Food items','supplier' => '','cost' => '9.5'),
            array('id' => '98','name' => 'SOMOLINA FLOUR','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.42'),
            array('id' => '99','name' => 'COCUNUT','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.33'),
            array('id' => '100','name' => 'COFFEE  ','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.95'),
            array('id' => '101','name' => 'ARABIC COFFEE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '3.25'),
            array('id' => '102','name' => 'FRENCH COFFEE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '3.2'),
            array('id' => '103','name' => 'CARAMEL SYRUP','unit' => 'ML','category' => 'Food items','supplier' => '','cost' => '1.925'),
            array('id' => '104','name' => 'WATER','unit' => 'ML','category' => 'Food items','supplier' => '','cost' => '0.1'),
            array('id' => '105','name' => 'TURKISH COFFEE','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '3.2'),
            array('id' => '106','name' => 'TEA ','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '4.15'),
            array('id' => '107','name' => 'GREEN TEA','unit' => 'Pcs','category' => 'Food items','supplier' => '','cost' => '1.39'),
            array('id' => '108','name' => 'DRY LEMON','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '1.304'),
            array('id' => '109','name' => 'DRY MARAMIYA','unit' => 'Grams','category' => 'Food items','supplier' => '','cost' => '0.9'),
            array('id' => '110','name' => 'GINGER','unit' => 'Grams','category' => 'Production','supplier' => '','cost' => '2.195'),
            array('id' => '111','name' => 'CLOVES','unit' => 'Grams','category' => 'Production','supplier' => '','cost' => '1.675'),
            array('id' => '112','name' => 'CHOCOLATE SAUCE','unit' => 'Grams','category' => 'Production','supplier' => '','cost' => '1.1'),
            array('id' => '113','name' => 'VANILLA GELATO','unit' => 'Grams','category' => 'Production','supplier' => '','cost' => '1.2'),
            array('id' => '114','name' => 'FRESH ORANGE','unit' => 'Grams','category' => 'Production','supplier' => '','cost' => '5.5'),
            array('id' => '115','name' => 'FRESH LEMON ','unit' => 'Grams','category' => 'Production','supplier' => '','cost' => '2.995'),
            array('id' => '116','name' => 'FRESH MINT ','unit' => 'Pcs','category' => 'Production','supplier' => '','cost' => '0.06'),
            array('id' => '117','name' => ' WILD MINT SYRUP ','unit' => 'ML','category' => 'Production','supplier' => '','cost' => '1.905'),
            array('id' => '118','name' => 'LEMON SYRUP ','unit' => 'ML','category' => 'Production','supplier' => '','cost' => '1.365'),
            array('id' => '119','name' => 'SUGAR SYRUP ','unit' => 'ML','category' => 'Production','supplier' => '','cost' => '0.31'),
            array('id' => '120','name' => 'FRESH LIME ','unit' => 'Grams','category' => 'Production','supplier' => '','cost' => '0.224'),
            array('id' => '121','name' => '7UP','unit' => 'ML','category' => 'Production','supplier' => '','cost' => '2.49'),
            array('id' => '122','name' => 'STRAWBERRY SYRUP','unit' => 'ML','category' => 'Production','supplier' => '','cost' => '1.905'),
            array('id' => '123','name' => ' CHOCOLATE GELATO','unit' => 'Grams','category' => 'Production','supplier' => '','cost' => '1.2'),
            array('id' => '124','name' => 'STRAWBERRY GELATO','unit' => 'Grams','category' => 'Production','supplier' => '','cost' => '1.2'),
            array('id' => '125','name' => 'LOTUS CREAM','unit' => 'Grams','category' => 'Production','supplier' => '','cost' => '0.49'),
            array('id' => '126','name' => 'HAZELNUT PASTE','unit' => 'Grams','category' => 'Production','supplier' => '','cost' => '4'),
            array('id' => '127','name' => 'APPLE ','unit' => 'Pcs','category' => 'Production','supplier' => '','cost' => '0.372'),
            array('id' => '128','name' => 'Saffron essence','unit' => 'Grams','category' => 'Production','supplier' => '','cost' => '0.42'),
            array('id' => '129','name' => 'CARAMEL PASTE','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '3.5'),
            array('id' => '130','name' => 'MIX NUTS','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '8'),
            array('id' => '131','name' => 'strawberry','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '2.495'),
            array('id' => '132','name' => 'GELATO PISTACHIO','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '1.2'),
            array('id' => '133','name' => 'GELATO HAZELNUT','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '1.2'),
            array('id' => '134','name' => 'GELATO CHERRY','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '1.2'),
            array('id' => '135','name' => 'CHERRY SAUCE','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '1.705'),
            array('id' => '136','name' => 'GELATO CHEESE CAKE','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '1.2'),
            array('id' => '137','name' => 'HUMMES CAN','unit' => 'Pcs','category' => 'ZNon Food','supplier' => '','cost' => '0.59'),
            array('id' => '138','name' => 'BLACK PEPPER','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.635'),
            array('id' => '139','name' => 'MASHROUM','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '1.095'),
            array('id' => '140','name' => 'ONION','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.347'),
            array('id' => '141','name' => 'TOMATO','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.475'),
            array('id' => '142','name' => 'CAPSICUM','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '1.195'),
            array('id' => '143','name' => 'CHEICKEN','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '1.39'),
            array('id' => '144','name' => 'SWEET CORN ','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '1.09'),
            array('id' => '145','name' => 'MAYONESE','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '1.38'),
            array('id' => '146','name' => 'PICKLE CUCUMBER','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.99'),
            array('id' => '147','name' => 'CHEEDAR CHEESE','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '1.115'),
            array('id' => '148','name' => 'BREAD TOAST','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.3'),
            array('id' => '149','name' => 'RICE','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '2.61'),
            array('id' => '150','name' => 'YOGURT','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.676'),
            array('id' => '151','name' => 'MASALA','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '4.6'),
            array('id' => '152','name' => 'TUMERIC','unit' => 'ML','category' => 'ZNon Food','supplier' => '','cost' => '0.69'),
            array('id' => '153','name' => 'CUMIN POWDER','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '4.9'),
            array('id' => '154','name' => 'CUREANDER','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.32'),
            array('id' => '155','name' => 'GREEN BEAN','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.49'),
            array('id' => '156','name' => 'POTATO','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.44'),
            array('id' => '157','name' => 'CHILI POWDER','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '1.566'),
            array('id' => '158','name' => 'SPICES MIX','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.275'),
            array('id' => '159','name' => 'TOMATO PASTE','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.75'),
            array('id' => '160','name' => 'PARSELY','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.1'),
            array('id' => '161','name' => 'CUCUMBER','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.75'),
            array('id' => '162','name' => 'BREAD ( NABIL )','unit' => 'Pcs','category' => 'ZNon Food','supplier' => '','cost' => '0.234'),
            array('id' => '163','name' => 'POMEGRANATE','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.94'),
            array('id' => '164','name' => 'VENEGAR','unit' => 'ML','category' => 'ZNon Food','supplier' => '','cost' => '0.263'),
            array('id' => '165','name' => 'CABAGE WHITE','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.13'),
            array('id' => '166','name' => 'BLUE CABAGE','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.295'),
            array('id' => '167','name' => 'CARROT','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.198'),
            array('id' => '168','name' => 'SPRING ONION','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.1'),
            array('id' => '169','name' => 'GARLIC','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.21'),
            array('id' => '170','name' => 'SOY SAUCE','unit' => 'ML','category' => 'ZNon Food','supplier' => '','cost' => '0.64'),
            array('id' => '171','name' => 'BEANS','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.935'),
            array('id' => '172','name' => 'NAKHI','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.214'),
            array('id' => '173','name' => 'FRENCH FRIES','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '1.595'),
            array('id' => '174','name' => 'EGGPLANTE','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.94'),
            array('id' => '175','name' => 'CHILLI','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.845'),
            array('id' => '176','name' => 'LABNAH','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '2.62'),
            array('id' => '177','name' => 'HALUMI CHEESE','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '4.08'),
            array('id' => '178','name' => 'FOUL CAN','unit' => 'Pcs','category' => 'ZNon Food','supplier' => '','cost' => '0.185'),
            array('id' => '179','name' => 'CARRY POWDER','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '2.34'),
            array('id' => '180','name' => 'FETA CHEESE','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.99'),
            array('id' => '181','name' => 'CHERRY TOMATO','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '0.99'),
            array('id' => '182','name' => 'HUMMES  ','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '1.1968'),
            array('id' => '183','name' => 'PARMESAN CHEESE','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '2.59'),
            array('id' => '184','name' => 'MOZARELLA CHEESE','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '1.48'),
            array('id' => '185','name' => 'MINCED MEAT','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '3'),
            array('id' => '186','name' => 'PUMPKIN','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '2.28'),
            array('id' => '187','name' => 'CELERY','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '2.21'),
            array('id' => '188','name' => 'LEEKS','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '1.99'),
            array('id' => '189','name' => 'SOUR CREAM','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '2.2'),
            array('id' => '190','name' => 'PUMPKIN SEEDS','unit' => 'Grams','category' => 'ZNon Food','supplier' => '','cost' => '2.77'),
            array('id' => '191','name' => 'Paper Buttlefly and flower  Design  Box','unit' => 'Pcs','category' => 'Packaging','supplier' => '','cost' => '1.25'),
            array('id' => '192','name' => 'Ice Cream Cups No-3','unit' => 'Pcs','category' => 'Packaging','supplier' => '','cost' => '0.0123'),
            array('id' => '193','name' => 'Cup Pop 100 CC Lime','unit' => 'Pcs','category' => 'Packaging','supplier' => '','cost' => '1.64'),
            array('id' => '194','name' => 'Ice Cream Cups No-4','unit' => 'Pcs','category' => 'Packaging','supplier' => '','cost' => '0.0153'),
            array('id' => '195','name' => 'BAMBOO BOX 7.5*4.5*H3.5 cm','unit' => 'Pcs','category' => 'Packaging','supplier' => '','cost' => '1.2'),
            array('id' => '196','name' => 'BAMBOO BOX 9.5*6.5*H4.5 cm','unit' => 'Pcs','category' => 'Packaging','supplier' => '','cost' => '1.2'),
            array('id' => '197','name' => 'BAMBOO BOX 11.5*8.5*H6 cm','unit' => 'Pcs','category' => 'Packaging','supplier' => '','cost' => '1.2'),
            array('id' => '198','name' => 'BAMBOO BOX 14.5*10.5*H8.5 cm','unit' => 'Pcs','category' => 'Packaging','supplier' => '','cost' => '1.2'),
            array('id' => '199','name' => ' Paper Flower And Butterfly  Design bag','unit' => 'Pcs','category' => 'Packaging','supplier' => '','cost' => '0.5'),
            array('id' => '200','name' => 'UV Treatment Embossyng Robe handle 42x25x37 cm','unit' => 'Pcs','category' => 'Packaging','supplier' => '','cost' => '0.75'),
            array('id' => '201','name' => 'UV Treatment Embossyng Robe handle 20.7x28.2x10.2 cm','unit' => 'Pcs','category' => 'Packaging','supplier' => '','cost' => '0.5'),
            array('id' => '202','name' => 'UV Treatment Embossyng Robe handle 27.5x23x14.2 cm','unit' => 'Pcs','category' => 'Packaging','supplier' => '','cost' => '0.5'),
            array('id' => '203','name' => 'UV Treatment Embossyng Robe handle14.2x18.8x8 cm','unit' => 'Pcs','category' => 'Packaging','supplier' => '','cost' => '0.25'),
            array('id' => '204','name' => 'CLEAR FOOD CONTAINER ( set with lid) 500ml T500','unit' => 'Pcs','category' => 'Packaging','supplier' => '','cost' => '0.25'),
            array('id' => '205','name' => '16oz/500ml "S" ripple wall cup','unit' => 'Pcs','category' => 'Packaging','supplier' => '','cost' => '0.15'),
            array('id' => '206','name' => '40z (118ml) Cic Hot Cup Single','unit' => 'Pcs','category' => 'Packaging','supplier' => '','cost' => '0.27'),
            array('id' => '207','name' => '12 oz(375ml) CIC Pet Plastic Cup','unit' => 'Pcs','category' => 'Packaging','supplier' => '','cost' => '0.29'),
            array('id' => '208','name' => 'PP HINGED Container to go box black','unit' => 'Pcs','category' => 'Packaging','supplier' => '','cost' => '0.2')
          );

          Item::insert($items);
    }
}
